export const restaurants = {
    Mexican: [
        { name: "Morra Mia", miles: 5.6, image: "../images/morra-mia.jpg", favorite: true, multipleLocations: true, link: "" },
        { name: "L&J", miles: 4.7, image: "../images/lj.jpg", link: "#" },
        { name: "Kiki's", miles: 5.5, image: "../images/kikis.jpg", link: "#" },
        { name: "Taconeta", miles: 1.7, image: "../images/taconeta.jpg", link: "https://www.google.com/search?sca_esv=e2532f7e453b1d7f&sxsrf=ANbL-n7HPBMrEvkS5N20ZzABnULWPifcEw:1770196490939&si=AL3DRZEsmMGCryMMFSHJ3StBhOdZ2-6yYkXd_doETEE1OR-qOVOGbKrqqaFP2kQcY69rfBsJATVrExzhZU9B4Vt34w1Y6kEJtM2igCgd6L1RgSd7BDbUERg0dHdGRv9Z_LJ3_hqPmDiU&q=Taconeta&sa=X&ved=2ahUKEwicsJnov7-SAxUs4skDHZPuF-UQ0bkNegQIMxAH&biw=1419&bih=871&dpr=1&aic=0" },
        { name: "Cometa", miles: 1.6, image: "../images/cometa.jpg", link: "https://www.google.com/search?q=cometa&sca_esv=e2532f7e453b1d7f&biw=1419&bih=871&aic=0&sxsrf=ANbL-n6goDZBBJbhLT3724RgOSf84DdlDA%3A1770196680367&ei=yA6DadWUFp3Jp84PreHvgAc&ved=0ahUKEwjVmMPCwL-SAxWd5MkDHa3wG3AQ4dUDCBM&uact=5&oq=cometa&gs_lp=Egxnd3Mtd2l6LXNlcnAiBmNvbWV0YTIKEAAYgAQYFBiHAjIWEC4YgAQYsQMYQxiDARjHARiKBRivATIKEAAYgAQYQxiKBTILEAAYgAQYkQIYigUyCBAAGIAEGMkDMgsQABiABBiSAxiKBTIFEAAYgAQyCBAAGIAEGLEDMgsQLhiABBjHARivATILEC4YgAQYxwEYrwFI0g1QwAhY9QxwA3gAkAEBmAGKAaAB3wWqAQMwLja4AQPIAQD4AQGYAgigApcFwgIKEAAYsAMY1gQYR8ICDRAAGLADGNYEGEcYyQPCAg4QABiABBiwAxiSAxiKBcICExAuGIAEGLADGEMYxwEYigUYrwHCAgoQIxiABBgnGIoFwgIREC4YgAQYkQIYxwEYigUYrwHCAgsQLhiABBjRAxjHAcICBBAjGCfCAgUQLhiABMICDhAuGIAEGMcBGI4FGK8BwgIIEC4YgAQYsQPCAgsQABiABBixAxiDAcICDhAuGIAEGLEDGNEDGMcBwgIQEC4YgAQYFBjHARiHAhivAZgDAIgGAZAGCpIHAzMuNaAHiGGyBwMwLjW4B44FwgcFMC4yLjbIBxuACAA&sclient=gws-wiz-serp&lqi=CgZjb21ldGEiA4gBAUjtup7jg6uAgAhaDBAAGAAiBmNvbWV0YZIBEm1leGljYW5fcmVzdGF1cmFudOABAA#rlimm=6954030492928106436" },
        { name: "Toro Bronco", miles: null, image: "../images/lj.jpg", link: "#" },
    ],
    Korean: [
        { name: "Gom Ramen", miles: 10.1, image: "../images/gom-ramen.jpg", link: "https://www.google.com/search?q=gom+ramen&sca_esv=e2532f7e453b1d7f&biw=1419&bih=871&aic=0&sxsrf=ANbL-n6rAPPYarCH5hiZg4UlThjG3EUaGg%3A1770196923363&ei=uw-DaYX2FY7Kp84P0OmjiQs&ved=0ahUKEwjFv7K2wb-SAxUO5ckDHdD0KLEQ4dUDCBM&uact=5&oq=gom+ramen&gs_lp=Egxnd3Mtd2l6LXNlcnAiCWdvbSByYW1lbjILEC4YgAQYxwEYrwEyCxAAGIAEGJECGIoFMgoQABiABBgUGIcCMgUQABiABDIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIaEC4YgAQYxwEYrwEYlwUY3AQY3gQY4ATYAQFIvBdQ_ApY2BNwAXgAkAEAmAGLAaABlAmqAQMxLjm4AQPIAQD4AQGYAgqgAoMJwgIKEAAYsAMY1gQYR8ICDRAjGPAFGIAEGCcYigXCAgoQIxiABBgnGIoFwgILEAAYgAQYsQMYgwHCAhYQLhiABBixAxjRAxhDGIMBGMcBGIoFwgIOEAAYgAQYsQMYgwEYigXCAhAQABiABBixAxhDGIMBGIoFwgIKEAAYgAQYQxiKBcICERAuGIAEGJECGMcBGIoFGK8BwgIIEC4YgAQYsQPCAgUQLhiABMICCxAuGIAEGLEDGIMBwgIgEC4YgAQYkQIYxwEYigUYrwEYlwUY3AQY3gQY4ATYAQHCAhAQLhiABBgUGMcBGIcCGK8BwgIIEAAYgAQYsQPCAgYQABgDGArCAh8QLhiABBgUGMcBGIcCGK8BGJcFGNwEGN4EGOAE2AEBwgIHEAAYgAQYCsICDRAuGIAEGNEDGMcBGArCAgIQJsICCxAAGIAEGIYDGIoFwgIIEAAYgAQYogSYAwCIBgGQBgi6BgYIARABGBSSBwMxLjmgB8ZtsgcDMC45uAeACcIHBzAuMS43LjLIBz-ACAA&sclient=gws-wiz-serp" },
        { name: "Café Korea", miles: 16.0, image: "../images/cafe-korea.jpg", link: "https://www.google.com/search?q=cafe+korea+el+paso&sca_esv=e2532f7e453b1d7f&biw=1419&bih=871&aic=0&sxsrf=ANbL-n4Sa-1xNFDEfmOHF2wXb9FeXiWNhA%3A1770197408288&ei=oBGDafisEZrJwN4PyI2uoA4&gs_ssp=eJzj4tVP1zc0TI8vLDTOMs81YLRSNaiwMEs1NzU3NTJIS0ozNUpKsTKoMDE1TDFKSk1MMkqzTDVMs_ASSk5MS1XIzi9KTVRIzVEoSCzOBwAacxZK&oq=cafe+korea&gs_lp=Egxnd3Mtd2l6LXNlcnAiCmNhZmUga29yZWEqAggNMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMg0QABiABBiwAxhDGIoFMg0QABiABBiwAxhDGIoFMg0QABiABBiwAxhDGIoFMg0QABiABBiwAxhDGIoFMhwQLhiABBiwAxhDGMcBGMgDGIoFGI4FGK8B2AEBMhkQLhiABBiwAxhDGMcBGMgDGIoFGK8B2AEBMhMQLhiABBiwAxhDGMgDGIoF2AEBMhMQLhiABBiwAxhDGMgDGIoF2AEBMg4QABiwAxjkAhjWBNgBATIOEAAYsAMY5AIY1gTYAQEyDhAAGLADGOQCGNYE2AEBSJUhUABYAHABeACQAQCYAW-gAW-qAQMwLjG4AQHIAQCYAgGgAgiYAwCIBgGQBhO6BgYIARABGAiSBwExoAeLF7IHALgHAMIHAzItMcgHBoAIAA&sclient=gws-wiz-serp" },
        { name: "Sushi House Moms", miles: 12.6, image: "../images/sushi-house-moms.jpg", favorite: true, link: "https://www.google.com/search?q=sushi+house+moms&biw=1419&bih=871&aic=0&sca_esv=e2532f7e453b1d7f&sxsrf=ANbL-n5FCIsMcR3OeeBugA9Y-kBrdMHpIQ%3A1770197441103&ei=wRGDadOBBrfep84PkJ21mAI&gs_ssp=eJzj4tVP1zc0zDK3LMkqTksyYLRSNaiwMEs1NzU0sUwytkg2TEs0tDKoMDSyNDVMM060BAqbmKVZeAkUlxZnZCpk5JcWpyrk5ucWAwDVYxUD&oq=sushi+house+mom&gs_lp=Egxnd3Mtd2l6LXNlcnAiD3N1c2hpIGhvdXNlIG1vbSoCCAoyDhAuGIAEGMcBGI4FGK8BMgoQABiABBgUGIcCMgUQABiABDIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMh0QLhiABBjHARiOBRivARiXBRjcBBjeBBjgBNgBAUiTNFCLDliaInADeAGQAQCYAZIBoAGkD6oBBDAuMTW4AQHIAQD4AQGYAhKgAowQwgIKEAAYsAMY1gQYR8ICDRAAGIAEGLADGEMYigXCAhwQLhiABBiwAxhDGMcBGMgDGIoFGI4FGK8B2AEBwgIZEC4YgAQYsAMYQxjHARjIAxiKBRivAdgBAcICDhAAGLADGOQCGNYE2AEBwgIKECMYgAQYJxiKBcICBBAjGCfCAgoQABiABBhDGIoFwgILEAAYgAQYkQIYigXCAhEQLhiABBiRAhjHARiKBRivAcICCxAuGIAEGNEDGMcBwgIQEC4YgAQYQxjHARiKBRivAcICEBAAGIAEGLEDGEMYyQMYigXCAgsQABiABBiSAxiKBcICCBAuGIAEGLEDwgIfEC4YgAQYQxjHARiKBRivARiXBRjcBBjeBBjgBNgBAcICExAuGIAEGEMYxwEYigUYjgUYrwHCAgsQLhiABBjHARivAcICFBAuGIAEGJECGMcBGIoFGI4FGK8BwgIIEAAYgAQYsQPCAiMQLhiABBiRAhjHARiKBRiOBRivARiXBRjcBBjeBBjgBNgBAcICExAuGIAEGBQYxwEYhwIYjgUYrwHCAiIQLhiABBgUGMcBGIcCGI4FGK8BGJcFGNwEGN4EGOAE2AEBwgIIEAAYgAQYyQPCAg0QLhiABBjHARgKGK8BmAMAiAYBkAYRugYGCAEQARgIkgcEMy4xNaAH64gCsgcEMC4xNbgH_g_CBwYwLjEuMTfIB1KACAA&sclient=gws-wiz-serp" },
        { name: "Garlic 1%", miles: 14.7, image: "../images/garlic-1.jpg", link: "https://www.google.com/search?q=garlic+1&biw=1419&bih=871&aic=0&sca_esv=e2532f7e453b1d7f&sxsrf=ANbL-n5ERaehWQmmXgXdqAZPodRzmF01mg%3A1770197558745&ei=NhKDacSbLfe9p84P6_L74As&gs_ssp=eJzj4tVP1zc0LM8qSM6wKM42YLRSNaiwMEs1NzE2MTIyNk42Mk8ytzKoSEoG8i3NTc3SkgxMkpNMvDjSE4tyMpMVDAFCvBHS&oq=garlic&gs_lp=Egxnd3Mtd2l6LXNlcnAiBmdhcmxpYyoCCAoyEBAuGIAEGEMYxwEYigUYrwEyCxAAGIAEGJECGIoFMgsQABiABBiRAhiKBTIKEAAYgAQYQxiKBTINEC4YgAQYsQMYQxiKBTIFEAAYgAQyChAAGIAEGEMYigUyChAAGIAEGEMYigUyCBAAGIAEGLEDMggQLhiABBixAzIfEC4YgAQYQxjHARiKBRivARiXBRjcBBjeBBjgBNgBAUjVHFDeB1jQDHADeAGQAQCYAZYBoAGPBqoBAzAuNrgBAcgBAPgBAZgCCaACxgbCAgoQABiwAxjWBBhHwgINEAAYsAMY1gQYRxjJA8ICDhAAGIAEGLADGJIDGIoFwgIKECMYgAQYJxiKBcICDRAjGPAFGIAEGCcYigXCAgsQLhiABBiRAhiKBcICCxAAGIAEGLEDGIMBwgIREC4YgAQYsQMY0QMYgwEYxwHCAg4QABiABBixAxiDARiKBcICERAuGIAEGJECGMcBGIoFGK8BwgINEC4YgAQYQxjlBBiKBcICDhAuGIAEGLEDGNEDGMcBwgILEC4YgAQYxwEYrwHCAhMQLhiABBixAxjRAxhDGMcBGIoFmAMAiAYBkAYKugYGCAEQARgUkgcDMy42oAfqb7IHAzAuNrgHtwbCBwMyLTnIBymACAA&sclient=gws-wiz-serp" },
        { name: "Kalbi House", miles: 9.2, image: "../images/kalbi-house.jpg", link: "https://www.google.com/search?q=kalbi+house+el+paso&biw=1419&bih=871&aic=0&sca_esv=e2532f7e453b1d7f&sxsrf=ANbL-n5kLbIgsuZyE8Qkn882hRWYgPXA1Q%3A1770197705848&ei=yRKDaY3FM6P-p84P-dXr0Qg&gs_ssp=eJzj4tZP1zcsSc8zNU1JMWC0UjWosDBLNTc1N0lJtjA0NkszT7EyqDBLSzY1SzJONTCyNDYzTjP3Es5OzEnKVMjILy1OVUjNUShILM4HAPMPFYU&oq=kalbi+house+el+paso&gs_lp=Egxnd3Mtd2l6LXNlcnAiE2thbGJpIGhvdXNlIGVsIHBhc28qAggHMg4QLhiABBjHARiOBRivATICECYyCxAAGIAEGIYDGIoFMgsQABiABBiGAxiKBTIFEAAY7wUyCBAAGKIEGIkFMgUQABjvBTIdEC4YgAQYxwEYjgUYrwEYlwUY3AQY3gQY4ATYAQFIv7gIUL2FCFiQmQhwBHgAkAEAmAGYAaABpxOqAQQwLjIwuAEByAEA-AEBmAIXoAK0E8ICChAAGLADGNYEGEfCAhMQLhiABBiwAxhDGMcBGIoFGK8BwgIQEAAYgAQYsAMYQxjJAxiKBcICChAjGIAEGCcYigXCAgoQABiABBhDGIoFwgILEC4YgAQY0QMYxwHCAhEQLhiABBixAxjRAxiDARjHAcICBRAAGIAEwgILEC4YgAQYsQMYgwHCAhEQLhiABBixAxjRAxjHARiKBcICERAuGIAEGJECGMcBGIoFGK8BwgILEC4YgAQYkQIYigXCAgoQLhiABBhDGIoFwgITEC4YgAQYFBiHAhjHARiOBRivAcICBBAAGAPCAiAQLhiABBiRAhjHARiKBRivARiXBRjcBBjeBBjgBNgBAcICFBAuGIAEGJECGMcBGIoFGI4FGK8BwgIKEAAYgAQYFBiHAsICCxAAGIAEGJECGIoFwgINEAAYgAQYsQMYQxiKBcICCBAuGIAEGLEDwgINEC4YgAQYsQMYQxiKBcICGRAuGIAEGEMYigUYlwUY3AQY3gQY3wTYAQHCAhMQLhiABBhDGMcBGIoFGI4FGK8BwgIQEC4YgAQYQxjHARiKBRivAcICBxAuGIAEGArCAgUQLhiABMICCxAuGIAEGMcBGK8BwgIGEAAYFhgewgIiEC4YgAQYFBiHAhjHARiOBRivARiXBRjcBBjeBBjgBNgBAZgDAIgGAZAGCroGBggBEAEYFJIHBDQuMTmgB6LyArIHBDAuMTm4B6QTwgcGMC4yLjIxyAdbgAgA&sclient=gws-wiz-serp" },
        { name: "Gen KBBQ", miles: 15.2, image: "../images/gen-bbq.jpg", link: "https://share.google/qcjxqAiNVOnwWuwGC" },
       
    ],
    American: [
        { name: "Shack Wings", miles: 9.8, image: "../images/shack.jpg", link: "https://www.google.com/search?q=shack+wings+el+paso&biw=1419&bih=871&aic=0&sca_esv=e2532f7e453b1d7f&sxsrf=ANbL-n5gIG1FCboTLYyfbSaKlnJ3mZybCQ%3A1770198025414&ei=CRSDabL-GMyFp84Pipi7uQU&ved=0ahUKEwjypvLDxb-SAxXMwskDHQrMLlcQ4dUDCBM&uact=5&oq=shack+wings+el+paso&gs_lp=Egxnd3Mtd2l6LXNlcnAiE3NoYWNrIHdpbmdzIGVsIHBhc28yChAAGLADGNYEGEcyChAAGLADGNYEGEcyChAAGLADGNYEGEcyChAAGLADGNYEGEcyChAAGLADGNYEGEcyChAAGLADGNYEGEcyChAAGLADGNYEGEcyChAAGLADGNYEGEdI1yBQ7QtYkxZwBXgBkAEAmAFpoAGnAqoBAzIuMbgBA8gBAPgBAZgCCKAC0gLCAgoQIxiABBgnGIoFwgIGEAAYFhgewgIIEAAYFhgKGB6YAwCIBgGQBgiSBwM1LjOgB98asgcDMC4zuAe7AsIHBTAuMS43yAcggAgA&sclient=gws-wiz-serp&lqi=ChNzaGFjayB3aW5ncyBlbCBwYXNvIgOIAQFI66jIyeWAgIAIWiEQABABGAAYARgCGAMiE3NoYWNrIHdpbmdzIGVsIHBhc2-SAQ1iYXJfYW5kX2dyaWxs4AEA#rlimm=1546296652438006603" },
        { name: "Union Draft House", miles: 5.3, image: "../images/union.jpg", link: "https://www.google.com/search?q=union+draft+house+el+paso&biw=1419&bih=871&aic=0&sca_esv=e2532f7e453b1d7f&sxsrf=ANbL-n4LZ3S6OZEBhRS56CQUAiKM0WdLJA%3A1770198032094&ei=EBSDaY7BBa7Fp84P84y4kAk&ved=0ahUKEwiOiYrHxb-SAxWu4skDHXMGDpIQ4dUDCBM&uact=5&oq=union+draft+house+el+paso&gs_lp=Egxnd3Mtd2l6LXNlcnAiGXVuaW9uIGRyYWZ0IGhvdXNlIGVsIHBhc28yBRAAGIAEMgUQABiABDIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgkQABgWGMkDGB4yCRAAGJIDGBYYHjIGEAAYFhgeMgYQABgWGB5IxTtQ7AZYxDFwAngBkAEAmAGOAaABjheqAQQwLjI1uAEDyAEA-AEBmAIboAK9GMICChAAGLADGNYEGEfCAgoQIxiABBgnGIoFwgIEECMYJ8ICCxAAGIAEGJECGIoFwgILEAAYgAQYsQMYgwHCAhEQLhiABBixAxjRAxiDARjHAcICDhAuGIAEGLEDGNEDGMcBwgIQEC4YgAQYQxjHARiKBRivAcICChAAGIAEGEMYigXCAgoQLhiABBhDGIoFwgIREC4YgAQYkQIYxwEYigUYrwHCAg0QABiABBixAxhDGIoFwgIZEC4YgAQYQxiKBRiXBRjcBBjeBBjgBNgBAcICEBAAGIAEGLEDGEMYgwEYigXCAg4QABiABBixAxiDARiKBcICCxAuGIAEGMcBGK8BwgIIEAAYgAQYyQPCAgsQABiABBiSAxiKBcICERAAGIAEGJECGLEDGIMBGIoFwgIREC4YgAQYkgMYxwEYjgUYrwHCAgoQABiABBgUGIcCmAMAiAYBkAYIugYGCAEQARgUkgcEMi4yNaAHrskCsgcEMC4yNbgHtxjCBwgwLjIuMjQuMcgHhAGACAA&sclient=gws-wiz-serp&lqi=Chl1bmlvbiBkcmFmdCBob3VzZSBlbCBwYXNvIgOIAQFIuZn33vm0gIAIWisQABABEAIYABgBGAIYAxgEIhl1bmlvbiBkcmFmdCBob3VzZSBlbCBwYXNvkgEKc3BvcnRzX2JhcuABAA#rlimm=6349931502887650980" },
        { name: "Angry Owl", miles: 2.8, image: "../images/angry-owl.jpg", link: "https://share.google/gKiiif07PHcGB4Gds" },
        { name: "Aurelia's Brewery", miles: 10.6, image: "../images/aurelias.jpg", link: "https://share.google/TiY8Ae2NvUzdaplo0" },
        { name: "Broken Rules Brewing", miles: 2.9, image: "../images/broken-rules.jpg", link: "https://share.google/ujvQMalHWf4SspAjl" },
        { name: "Boss Tenders", miles: null, image: "../images/boss.jpg", link: "https://share.google/Gghz7pYR053sfeTen" },
        { name: "Crave", miles: 0.8, image: "../images/broken-rules.jpg", link: "https://share.google/XMfqqdJMRCuEVeO6X" },
        { name: "Neighbor Good", miles: 4.2, image: "../images/broken-rules.jpg", link: "https://share.google/W0j42yBXoZtbG44sR" },
    ],
    Brunch:[
        {},
    ],
    Asian: [
        { name: "Kaedamma", miles: 0.9, image: "../images/kaedamma.jpg", link: "https://share.google/UbY4LttqwTI71PTml" },
        { name: "Koze", miles: 5.0, image: "../images/koze.jpg", link: "https://share.google/A3IpH0YEfZeqhhLU1" },
        { name: "China Town", miles: 11.0, image: "../images/china-town.jpg", link: "https://share.google/83VHrOdQWRWzTPA4g" },
        { name: "Tara Thai", miles: 0.8, image: "../images/tara-thai.jpg", link: "https://share.google/E0I0VR8vWRuWPhu5w" },
        { name: "Sunny's Sushi", miles: 1.4, image: "../images/sunnys-sushi.jpg", link: "https://www.google.com/search?q=sunnys+sushi+el+paso&biw=1419&bih=871&aic=0&sca_esv=e2532f7e453b1d7f&sxsrf=ANbL-n6ETjRz6vGbZeSeKPtmCGg_bVDIMA%3A1770199307069&ei=CxmDabr-A4rEp84Pjs3F0QE&ved=0ahUKEwj6r4Snyr-SAxUK4skDHY5mMRoQ4dUDCBM&uact=5&oq=sunnys+sushi+el+paso&gs_lp=Egxnd3Mtd2l6LXNlcnAiFHN1bm55cyBzdXNoaSBlbCBwYXNvMgsQABiABBiRAhiKBTILEAAYgAQYkQIYigUyCxAAGIAEGJECGIoFMgsQABiABBiRAhiKBTIJEAAYgAQYChgLMgYQABgWGB4yCBAAGBYYChgeMgYQABgWGB4yCBAAGBYYChgeMgYQABgWGB5IiUBQtQhYsT1wAngBkAEAmAGcAaABoRSqAQQwLjIwuAEDyAEA-AEBmAIWoAKrFcICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFwgIcEC4YgAQYsAMYQxjHARjIAxiKBRiOBRivAdgBAcICExAuGIAEGLADGEMYyAMYigXYAQHCAhkQLhiABBiwAxhDGMcBGMgDGIoFGK8B2AEBwgIKECMYgAQYJxiKBcICExAuGIAEGMcBGCcYigUYjgUYrwHCAgoQABiABBhDGIoFwgIQEC4YgAQYQxjHARiKBRivAcICEBAuGIAEGNEDGEMYxwEYigXCAgsQLhiABBjRAxjHAcICBBAjGCfCAg0QABiABBixAxhDGIoFwgIgEC4YgAQYxwEYigUYjgUYrwEYlwUY3AQY3gQY4ATYAQHCAgoQIxjwBRgnGMkCwgITEC4YgAQYQxjHARiKBRiOBRivAcICERAuGIAEGJECGMcBGIoFGK8BwgIIEAAYgAQYsQPCAgUQABiABMICCBAuGIAEGLEDwgIKEC4YgAQYQxiKBcICBxAAGIAEGArCAgoQABiABBgUGIcCwgITEC4YgAQYsQMYgwEYxwEYChivAcICChAAGIAEGMkDGArCAgoQABiABBiSAxgKwgILEAAYgAQYkgMYigXCAg0QLhiABBjHARgKGK8BwgIQEC4YgAQYxwEYChiOBRivAcICCRAAGBYYyQMYHpgDAIgGAZAGE7oGBggBEAEYCJIHBDIuMjCgB5bJArIHBDAuMjC4B5wVwgcEMi0yMsgHZ4AIAA&sclient=gws-wiz-serp" },
        { name: "Love Pho", miles: 6.7, image: "../images/china-town.jpg", link: "https://share.google/trmXgYwMaKhdM56vz" },
    ],
    "Pizza/Italian": [
        { name: "Ardovinos", miles: 0.8, image: "../images/ardovinos.jpg", link: "https://www.google.com/search?q=ardovinos+el+paso&oq=ardovinos+el+paso&gs_lcrp=EgZjaHJvbWUqDggAEEUYJxg7GIAEGIoFMg4IABBFGCcYOxiABBiKBTIHCAEQABiABDIHCAIQABiABDIHCAMQABiABDIICAQQABgWGB4yCAgFEAAYFhgeMggIBhAAGBYYHjIICAcQABgWGB4yCggIEAAYChgWGB4yCggJEAAYChgWGB7SAQgzNjAyajBqN6gCCLACAfEFSkxz7JFUnzk&sourceid=chrome&ie=UTF-8" },
        { name: "Pizza Joint", miles: 0.9, image: "../images/pizza-joint.jpg", link: "https://share.google/2HThO7FiDqze2zGp1" },
        { name: "Deserto Pizza", miles: 4.5, image: "../images/deserto-pizza.jpg", link: "https://share.google/J35tXyAuK5pqnclng" },
        { name: "Peter Piper Pizza", miles: 5.0, image: "../images/peter-piper.jpg", link: "https://share.google/0I86GRV8iifBQKYjm" },
        { name: "Italian Kitchen", miles: 4.5, image: "../images/italian-kitchen.jpg", link: "https://share.google/X30nQTo0eyoCFQuWq" }
    ],
    "Cafes/Matcha": [
        { name: "My Favorite Matcha", miles: 4.5, image: "../images/my-favorite-matcha.png", link: "https://share.google/LPUp9cpfmWQ2JR2Tq" },
        { name: "787 Coffee", miles: 0.9, image: "../images/787-coffee.jpg", link: "https://share.google/nAq9sx4uBAin6bYCp" },
        { name: "Viejo Coffee", miles: 0.9, image: "../images/viejo-coffee.jpg", link: "https://share.google/HJsE780rpB9nPkaem" },
        { name: "Brewnergy", miles: 0.8, image: "../images/brewnergy.jpg", link: "https://share.google/9IOwGFkZdfJnkeVRH" },
        { name: "Coffee Box", miles: 2.0, image: "../images/coffee-box.jpg", link: "https://share.google/kh1us352jlpS8SQ1S" }
    ]
};

export const categoryPhotos = {
    All: "../images/tata-red-lg.png",
    Mexican: "../images/koya-blue.png",
    Korean: "../images/shooky-purple.png",
    American: "../images/rj-red.png",
    Asian: "../images/cooky.png",
    "Pizza/Italian": "../images/chimmy.png",
    "Cafes/Matcha": "../images/mang.png"
};